#!/usr/bin/env bash
# The first line of this file, or the `hashbang`, tells the system to
# execute the text of this file as a bash program.

# Hello, welcome to a bash script.

# This bash script deploys your boilermaker application.

# On the terminal you run individual
# bash commands, and this file strings a bunch of commands together.

# We want this entire script to exit if any single line fails.
# So we set the `-e` flag.
set -e

node 

const fs = require('fs')

fs.writeFile('secrets.json', `{
 "type": "service_account",
 "project_id": "test1-211018",
 "private_key_id": "${process.env.private_key_id}",
 "private_key": "-----BEGIN PRIVATE KEY-----\n${process.env.private_key}\n-----END PRIVATE KEY-----\n",
 "client_email": "whats-that@test1-211018.iam.gserviceaccount.com",
 "client_id": "103346616138126366479",
 "auth_uri": "https://accounts.google.com/o/oauth2/auth",
 "token_uri": "https://oauth2.googleapis.com/token",
 "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
 "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/whats-that%40test1-211018.iam.gserviceaccount.com"
}`, (err) => {if (err) throw err})

export GOOGLE_APPLICATION_CREDENTIALS = process.cwd() + '/secrets.json'

.exit